import React, { useState } from 'react';

function formatAsJSON(data) {
  return JSON.stringify(data, null, 2);
}

// AS3 fields have no fixed memory offset (AVM2 decides slot allocation
// at runtime), so the dumper emits offset=null. We render those as
// "<runtime>" in CSV and skip them in the C++ header with a comment.
function fmtOffset(offset) {
  if (offset == null) return '<runtime>';
  return '0x' + offset.toString(16).toUpperCase();
}

function formatAsCSV(data) {
  const rows = ['Class,Field,Offset,Type,Size'];
  (data.classes || []).forEach(cls => {
    (cls.fields || []).forEach(f => {
      rows.push(`${cls.name},${f.name},${fmtOffset(f.offset)},${f.type || ''},${f.size ?? ''}`);
    });
  });
  return rows.join('\n');
}

function formatAsCppHeader(data) {
  const lines = [
    '// Generated by BIFROST SDK v4.0.0',
    `// Engine: ${data.engine || 'Unknown'}`,
    data.strategy ? `// Strategy: ${data.strategy}` : null,
    `// Date: ${new Date().toISOString()}`,
    '#pragma once',
    '#include <cstdint>',
    '',
    'namespace offsets {',
  ].filter(Boolean);
  (data.classes || []).forEach(cls => {
    const runtimeOnly = (cls.fields || []).filter(f => f.offset == null);
    const fixedFields = (cls.fields || []).filter(f => f.offset != null);
    lines.push(`  namespace ${cls.name.replace(/[^a-zA-Z0-9_]/g, '_')} {`);
    fixedFields.forEach(f => {
      const name = f.name.replace(/[^a-zA-Z0-9_]/g, '_');
      lines.push(`    constexpr uintptr_t ${name} = 0x${f.offset.toString(16).toUpperCase()}; // ${f.type || ''}`);
    });
    // AS3/runtime-layout fields can't be emitted as compile-time constants —
    // surface them as a comment so the user knows the field exists.
    if (runtimeOnly.length > 0) {
      lines.push(`    // Runtime-layout fields (no fixed offset, e.g. AS3 slots):`);
      runtimeOnly.forEach(f => {
        lines.push(`    //   ${f.name} : ${f.type || ''}`);
      });
    }
    lines.push('  }');
    lines.push('');
  });
  lines.push('}');
  return lines.join('\n');
}

export default function ResultsPage({ data, setPage }) {
  const [activeClass, setActiveClass] = useState(null);
  const [exportMsg, setExportMsg] = useState('');
  const [copied, setCopied] = useState(false);

  const copyToClipboard = (format) => {
    let content;
    if (format === 'cpp') content = formatAsCppHeader(data);
    else if (format === 'json') content = formatAsJSON(data);
    else return;
    navigator.clipboard.writeText(content).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const api = window.bifrost;

  const exportData = async (format) => {
    let content, ext, mime;
    switch (format) {
      case 'json':
        content = formatAsJSON(data);
        ext = 'json';
        mime = 'application/json';
        break;
      case 'csv':
        content = formatAsCSV(data);
        ext = 'csv';
        mime = 'text/csv';
        break;
      case 'cpp':
        content = formatAsCppHeader(data);
        ext = 'h';
        mime = 'text/plain';
        break;
      default: return;
    }

    // Try Electron save dialog first, fallback to browser download
    if (api?.saveFile) {
      try {
        const result = await api.saveFile({
          content,
          defaultName: `bifrost_dump.${ext}`,
          filters: [{ name: format.toUpperCase(), extensions: [ext] }],
        });
        if (result?.saved) {
          setExportMsg(`Saved to ${result.path}`);
          setTimeout(() => setExportMsg(''), 3000);
          return;
        }
      } catch (err) {
        setExportMsg('Export failed');
        setTimeout(() => setExportMsg(''), 3000);
      }
    }

    // Browser fallback
    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `bifrost_dump.${ext}`;
    a.click();
    URL.revokeObjectURL(url);
    setExportMsg('Downloaded');
    setTimeout(() => setExportMsg(''), 3000);
  };

  // Support both full shape (data.classes = array of objects) and summary shape from live bridge
  // (data = { headers, json: path, classes: count, fields: count, engine, elapsed, ... })
  const classesArray = Array.isArray(data?.classes) ? data.classes : [];
  const isSummaryShape = typeof data?.classes === 'number';

  if (!data || (isSummaryShape ? data.classes === 0 : classesArray.length === 0)) {
    return (
      <>
        <div className="page-header">
          <div className="page-title">Results</div>
          <div className="page-subtitle">Dumped offsets will appear here after a scan completes</div>
        </div>
        <div className="log-console" style={{ textAlign: 'center', padding: 40 }}>
          <p className="log-line dim">No results yet. Run a dump to see offsets here.</p>
          <button
            className="btn btn-primary"
            style={{ marginTop: 16 }}
            onClick={() => setPage('dump')}
          >
            Go to Dump
          </button>
        </div>
      </>
    );
  }

  const selectedClass = (isSummaryShape ? null : classesArray.find(c => c.name === activeClass) || classesArray[0]);

  return (
    <>
      <div className="page-header">
        <div className="page-title">
          Results
          {exportMsg && <span style={{ marginLeft: 12, color: 'var(--shatter-green)', fontSize: 12, fontWeight: 400 }}>{exportMsg}</span>}
        </div>
        <div className="page-subtitle" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <span>
            {isSummaryShape ? `${data.classes} classes found` : `${classesArray.length} classes found`} 
            - {data.total_fields || data.fields || 0} fields total
            {isSummaryShape && data.json && <span style={{ marginLeft: 8, fontSize: '0.8em', color: 'var(--text-dim)' }}>(summary - full data in {data.json})</span>}
          </span>
          <div className="btn-group" style={{ margin: 0, padding: 0 }}>
            <button className="btn btn-secondary" onClick={() => copyToClipboard('cpp')} title="Copy C++ header to clipboard">
              {copied ? 'Copied!' : 'Copy C++'}
            </button>
            <button className="btn btn-secondary" onClick={() => exportData('json')} title="Export as JSON">JSON</button>
            <button className="btn btn-secondary" onClick={() => exportData('csv')} title="Export as CSV">CSV</button>
            <button className="btn btn-secondary" onClick={() => exportData('cpp')} title="Export as C++ header">C++ .h</button>
          </div>
        </div>
      </div>

      <div className="stats-row">
        <div className="stat-card">
          <div className="stat-label">Classes</div>
          <div className="stat-value">{isSummaryShape ? data.classes : classesArray.length}</div>
        </div>
        <div className="stat-card">
          <div className="stat-label">Fields</div>
          <div className="stat-value">{data.total_fields || data.fields || 0}</div>
        </div>
        <div className="stat-card">
          <div className="stat-label">Engine</div>
          <div className="stat-value">
            {data.engine || '-'}
            {data.strategy === 'swf' && (
              <span style={{
                display: 'block',
                fontSize: '0.55em',
                fontWeight: 600,
                marginTop: 4,
                color: 'var(--accent, #f5a623)',
                letterSpacing: '0.5px',
              }}>
                STRATEGY: SWF / AS3
              </span>
            )}
            {data.strategy === 'memory' && (
              <span style={{
                display: 'block',
                fontSize: '0.55em',
                fontWeight: 600,
                marginTop: 4,
                color: 'var(--text-ghost)',
                letterSpacing: '0.5px',
              }}>
                STRATEGY: MEMORY (LEGACY)
              </span>
            )}
          </div>
        </div>
      </div>

      <div className="results-panel">
        <div className="class-tree">
          {(isSummaryShape ? [] : classesArray).map((cls) => (
            <div
              key={cls.name}
              className={`tree-node ${(activeClass || (classesArray[0]?.name)) === cls.name ? 'active' : ''}`}
              onClick={() => setActiveClass(cls.name)}
            >
              <span className="class-name">{cls.name}</span>
              <span className="class-size">{cls.size ? `0x${cls.size.toString(16).toUpperCase()}` : ''}</span>
            </div>
          ))}
          {isSummaryShape && (
            <div style={{ padding: 12, color: 'var(--text-dim)', fontSize: '0.9em' }}>
              Full class data is in the JSON file on disk.<br />
              Use "Load JSON" in other tools or the path above to explore.
            </div>
          )}
        </div>

        <div className="field-table-wrapper">
          <table className="field-table">
            <thead>
              <tr>
                <th>Offset</th>
                <th>Name</th>
                <th>Type</th>
                <th>Size</th>
              </tr>
            </thead>
            <tbody>
              {(selectedClass?.fields || []).map((field, i) => (
                <tr key={i}>
                  <td className="offset">{fmtOffset(field.offset)}</td>
                  <td>{field.name}</td>
                  <td className="type">{field.type}</td>
                  <td>{field.size ?? '-'}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </>
  );
}
