import React, { useState, useContext } from 'react';
import { ToastContext } from '../App';

function formatAsJSON(data) {
  return JSON.stringify(data, null, 2);
}

// AS3 fields have no fixed memory offset (AVM2 decides slot allocation
// at runtime), so the dumper emits offset=null. We render those as
// "<runtime>" in CSV and skip them in the C++ header with a comment.
function fmtOffset(offset) {
  if (offset == null) return '<runtime>';
  return '0x' + offset.toString(16).toUpperCase();
}

function formatAsCSV(data) {
  const rows = ['Class,Field,Offset,Type,Size'];
  (data.classes || []).forEach(cls => {
    (cls.fields || []).forEach(f => {
      rows.push(`${cls.name},${f.name},${fmtOffset(f.offset)},${f.type || ''},${f.size ?? ''}`);
    });
  });
  return rows.join('\n');
}

function formatAsCppHeader(data) {
  const lines = [
    '// Generated by BIFROST SDK v4.0.0',
    `// Engine: ${data.engine || 'Unknown'}`,
    data.strategy ? `// Strategy: ${data.strategy}` : null,
    `// Date: ${new Date().toISOString()}`,
    '#pragma once',
    '#include <cstdint>',
    '',
    'namespace offsets {',
  ].filter(Boolean);
  (data.classes || []).forEach(cls => {
    const runtimeOnly = (cls.fields || []).filter(f => f.offset == null);
    const fixedFields = (cls.fields || []).filter(f => f.offset != null);
    lines.push(`  namespace ${cls.name.replace(/[^a-zA-Z0-9_]/g, '_')} {`);
    fixedFields.forEach(f => {
      const name = f.name.replace(/[^a-zA-Z0-9_]/g, '_');
      lines.push(`    constexpr uintptr_t ${name} = 0x${f.offset.toString(16).toUpperCase()}; // ${f.type || ''}`);
    });
    // AS3/runtime-layout fields can't be emitted as compile-time constants —
    // surface them as a comment so the user knows the field exists.
    if (runtimeOnly.length > 0) {
      lines.push(`    // Runtime-layout fields (no fixed offset, e.g. AS3 slots):`);
      runtimeOnly.forEach(f => {
        lines.push(`    //   ${f.name} : ${f.type || ''}`);
      });
    }
    lines.push('  }');
    lines.push('');
  });
  lines.push('}');
  return lines.join('\n');
}

export default function ResultsPage({ data, setPage, setDumpResults }) {
  const [activeClass, setActiveClass] = useState(null);
  const [exportMsg, setExportMsg] = useState('');
  const [copied, setCopied] = useState(false);
  const [loadMsg, setLoadMsg] = useState('');
  const [loading, setLoading] = useState(false);
  const toast = useContext(ToastContext);

  const showToast = (msg, type = 'success') => {
    if (window.bifrost?.toast) window.bifrost.toast(msg, type);
    else if (toast) toast(msg, type);
  };

  // Recover from a lost live result: pick the offsets.json on disk and
  // rebuild a summary view from its _meta. Fixes the "dump said done but
  // the page is empty" case (backend restart, page opened late, ...).
  const loadFromDisk = async () => {
    const api = window.bifrost;
    if (!api?.loadJsonFile) return;
    if (loading) return;
    setLoading(true);
    try {
      const res = await api.loadJsonFile();
      if (!res?.data || res.cancelled) return;
      const meta = res.data._meta || {};
      const offsets = res.data.offsets || {};
      const totalFields = Object.values(offsets).reduce(
        (acc, entry) => acc + (entry && entry.fields ? Object.keys(entry.fields).length : 0),
        0
      );
      const summary = {
        classes: meta.total_classes ?? Object.keys(offsets).length,
        fields: meta.total_fields ?? totalFields,
        engine: meta.engine || '',
        headers: [],
        json: res.filename,
      };
      if (setDumpResults) setDumpResults(summary);
      setLoadMsg(`Loaded ${res.filename}`);
      setTimeout(() => setLoadMsg(''), 4000);
    } catch (err) {
      setLoadMsg('Failed to read that file');
      setTimeout(() => setLoadMsg(''), 4000);
    } finally {
      setLoading(false);
    }
  };

  // Live dumps come back as a summary (counts + path, no rows). This pulls the
  // offsets.json off disk and expands it into a browsable class list, so the
  // Results page isn't stuck with an empty table after every real dump.
  const loadFullFromDisk = async () => {
    const api = window.bifrost;
    if (!api?.loadJsonFile) return;
    if (loading) return;
    setLoading(true);
    try {
      const res = await api.loadJsonFile();
      if (!res?.data || res.cancelled) return;
      const file = res.data;
      const hexToNum = (v) => (typeof v === 'string' ? parseInt(v, 16) : v);
      const classes = Object.entries(file.offsets || {}).map(([name, entry]) => ({
        name,
        size: entry?.size != null ? hexToNum(entry.size) : undefined,
        super: entry?.super,
        fields: Object.entries(entry?.fields || {}).map(([fieldName, f]) => ({
          name: fieldName,
          offset: typeof f === 'object' ? hexToNum(f.offset) : hexToNum(f),
          type: typeof f === 'object' ? f.type : undefined,
          size: typeof f === 'object' ? f.size : undefined,
        })),
      }));
      const meta = file._meta || {};
      const totalFields = classes.reduce((acc, c) => acc + c.fields.length, 0);
      if (setDumpResults) {
        setDumpResults({
          classes,
          fields: meta.total_fields ?? totalFields,
          engine: meta.engine || '',
          json: res.filename,
          headers: Array.isArray(file.headers) ? file.headers : [],
          _loadedFromDisk: true,
        });
      }
      setLoadMsg(`Loaded ${classes.length} classes from ${res.filename}`);
      setTimeout(() => setLoadMsg(''), 4000);
    } catch (err) {
      setLoadMsg('Failed to read that file');
      setTimeout(() => setLoadMsg(''), 4000);
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = (format) => {
    // Guard: C++ export from summary shape has no fields
    if (format === 'cpp' && typeof data?.classes === 'number') {
      showToast('Load full JSON first', 'error');
      return;
    }
    let content;
    if (format === 'cpp') content = formatAsCppHeader(data);
    else if (format === 'json') content = formatAsJSON(data);
    else if (format === 'csv') content = formatAsCSV(data);
    else return;
    const fallback = window.bifrost?.copyWithToast
      ? (t) => window.bifrost.copyWithToast(t, 'Copied to clipboard')
      : window.bifrost?.toast
        ? async (t) => { await navigator.clipboard.writeText(t); window.bifrost.toast('Copied to clipboard', 'success'); }
        : async (t) => { await navigator.clipboard.writeText(t); toast && toast('Copied to clipboard', 'success'); };
    fallback(content).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
      // Ensure toast for JSON/CSV as well (copyWithToast already does, but window.bifrost.toast path above covers it)
      if (format === 'json' || format === 'csv') {
        // copyWithToast already toasted; for direct clipboard path we already toasted. No-op.
      }
    }).catch(() => showToast('Copy failed', 'error'));
  };

  const api = window.bifrost;

  const exportData = async (format) => {
    if (format === 'cpp' && typeof data?.classes === 'number') {
      showToast('Load full JSON first', 'error');
      return;
    }
    let content, ext, mime;
    switch (format) {
      case 'json':
        content = formatAsJSON(data);
        ext = 'json';
        mime = 'application/json';
        break;
      case 'csv':
        content = formatAsCSV(data);
        ext = 'csv';
        mime = 'text/csv';
        break;
      case 'cpp':
        content = formatAsCppHeader(data);
        ext = 'h';
        mime = 'text/plain';
        break;
      default: return;
    }

    // Try Electron save dialog first, fallback to browser download
    if (api?.saveFile) {
      try {
        const result = await api.saveFile({
          content,
          defaultName: `bifrost_dump.${ext}`,
          filters: [{ name: format.toUpperCase(), extensions: [ext] }],
        });
        if (result?.saved) {
          setExportMsg(`Saved to ${result.path}`);
          showToast(`Saved to ${result.path}`, 'success');
          setTimeout(() => setExportMsg(''), 3000);
          return;
        }
      } catch (err) {
        setExportMsg('Export failed');
        showToast('Export failed', 'error');
        setTimeout(() => setExportMsg(''), 3000);
      }
    }

    // Browser fallback
    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `bifrost_dump.${ext}`;
    a.click();
    URL.revokeObjectURL(url);
    setExportMsg('Downloaded');
    showToast('Downloaded', 'success');
    setTimeout(() => setExportMsg(''), 3000);
  };

  // Support both full shape (data.classes = array of objects) and summary shape from live bridge
  // (data = { headers, json: path, classes: count, fields: count, engine, elapsed, ... })
  const classesArray = Array.isArray(data?.classes) ? data.classes : [];
  const isSummaryShape = typeof data?.classes === 'number';

  if (!data || (isSummaryShape ? data.classes === 0 : classesArray.length === 0)) {
    return (
      <>
        <div className="page-header">
          <div className="page-title">Results</div>
          <div className="page-subtitle">Dumped offsets will appear here after a scan completes</div>
        </div>
        <div className="empty-state" style={{ padding: 36, gap: 10 }}>
          <div className="empty-title">No live results</div>
          <p className="empty-hint">If a dump just finished, its files are on disk — load the offsets.json to view the summary.</p>
          <div className="empty-action" style={{ display: 'flex', gap: 8, alignItems: 'center', justifyContent: 'center', marginTop: 4 }}>
            <button
              className="btn btn-primary"
              onClick={() => setPage('dump')}
            >
              Go to Dump
            </button>
            <button
              className="btn"
              onClick={loadFromDisk}
              disabled={loading}
              style={{ fontSize: 12 }}
            >
              {loading ? 'Loading...' : 'Load offsets.json from disk'}
            </button>
          </div>
          {loadMsg && <p className="log-line dim" style={{ fontSize: 11, marginTop: 6 }}>{loadMsg}</p>}
        </div>
      </>
    );
  }

  const selectedClass = (isSummaryShape ? null : classesArray.find(c => c.name === activeClass) || classesArray[0]);
  const activeName = activeClass || classesArray[0]?.name;

  return (
    <>
      <div className="page-header" style={{ display: 'flex', alignItems: 'baseline', gap: 10, flexWrap: 'wrap' }}>
        <div className="page-title" style={{ display: 'flex', alignItems: 'center', gap: 8 }}><span style={{ width: 3, height: 14, background: '#7EFF3F', boxShadow: '0 0 6px rgba(126,255,63,0.45)', borderRadius: 1, display: 'inline-block' }} />Results
          {exportMsg && <span className="mono-hint success">{exportMsg}</span>}
          {loadMsg && <span className="mono-hint info">{loadMsg}</span>}
        </div>
        <span style={{ fontFamily: 'var(--font-mono)', fontSize: 10, color: 'var(--text-ghost)', letterSpacing: '0.08em' }}>● DUMP  <span style={{ color: '#7EFF3F' }}>{isSummaryShape ? data.classes : classesArray.length} CLASSES</span></span>
        <div className="page-subtitle mono-row" style={{ width: '100%', marginTop: 2 }}>
          <span>
            {isSummaryShape ? `${data.classes} classes found` : `${classesArray.length} classes found`}
            <span className="dim"> — {data.total_fields || data.fields || 0} fields total</span>
            {isSummaryShape && data.json && <span className="dim mono-path"> (summary — {data.json})</span>}
          </span>
          <div className="btn-group tight">
            {isSummaryShape && (
              <button className="btn" onClick={loadFullFromDisk} disabled={loading} title="Read the offsets.json from disk and list every class" style={{ fontSize: 12 }}>
                {loading ? 'Loading...' : 'Load full JSON'}
              </button>
            )}
            <button className="btn" onClick={() => copyToClipboard('json')} title="Copy JSON to clipboard" style={{ fontSize: 12 }}>Copy JSON</button>
            <button className="btn" onClick={() => copyToClipboard('csv')} title="Copy CSV to clipboard" style={{ fontSize: 12 }}>Copy CSV</button>
            <button className="btn" onClick={() => copyToClipboard('cpp')} title="Copy C++ header to clipboard" style={{ fontSize: 12 }}>
              {copied ? 'Copied!' : 'Copy C++'}
            </button>
            <button className="btn" onClick={() => exportData('json')} title="Export as JSON" style={{ fontSize: 12 }}>JSON</button>
            <button className="btn" onClick={() => exportData('csv')} title="Export as CSV" style={{ fontSize: 12 }}>CSV</button>
            <button
              className="btn btn-primary"
              onClick={() => exportData('cpp')}
              disabled={isSummaryShape}
              title={isSummaryShape ? 'Load full JSON first' : 'Export as C++ header'}
            >
              C++ .h
            </button>
          </div>
        </div>
      </div>

      <div className="stats-row">
        <div className="stat-card">
          <div className="stat-label">Classes</div>
          <div className="stat-value">{isSummaryShape ? data.classes : classesArray.length}</div>
        </div>
        <div className="stat-card">
          <div className="stat-label">Fields</div>
          <div className="stat-value">{data.total_fields || data.fields || 0}</div>
        </div>
        <div className="stat-card">
          <div className="stat-label">Engine</div>
          <div className="stat-value">
            {data.engine || '-'}
            {data.strategy === 'swf' && <span className="strategy-badge swf">STRATEGY: SWF / AS3</span>}
            {data.strategy === 'memory' && <span className="strategy-badge memory">STRATEGY: MEMORY (LEGACY)</span>}
          </div>
        </div>
      </div>

      <div className="results-panel">
        <div className="class-tree">
          {(isSummaryShape ? [] : classesArray).map((cls) => {
            const isActive = activeName === cls.name;
            return (
              <div
                key={cls.name}
                role="button"
                tabIndex={0}
                aria-selected={isActive}
                className={`tree-node ${isActive ? 'active' : ''}`}
                onClick={() => setActiveClass(cls.name)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' || e.key === ' ') {
                    e.preventDefault();
                    setActiveClass(cls.name);
                  }
                }}
              >
                <span className="class-name">{cls.name}</span>
                <span className="class-size">{cls.size ? `0x${cls.size.toString(16).toUpperCase()}` : ''}</span>
              </div>
            );
          })}
          {isSummaryShape && (
            <div style={{ padding: 12, borderTop: '1px dashed rgba(255,255,255,0.08)', marginTop: 8 }}>
              <p style={{ color: 'var(--text-muted)', fontSize: 11, marginBottom: 10, lineHeight: 1.5, fontFamily: 'var(--font-mono)' }}>
                Summary — class list not loaded.
                {data.json && (
                  <>
                    {' '}Full data is in <span className="dim" style={{ wordBreak: 'break-all', color: 'var(--text-ghost)' }}>{data.json}</span>.
                  </>
                )}
              </p>
              <button
                className="btn btn-primary"
                onClick={loadFullFromDisk}
                disabled={loading}
                style={{ width: '100%' }}
              >
                {loading ? 'Loading...' : 'Load full JSON'}
              </button>
            </div>
          )}
        </div>

        <div className="field-table-wrapper">
          <table className="field-table">
            <thead>
              <tr>
                <th>Offset</th>
                <th>Name</th>
                <th>Type</th>
                <th>Size</th>
              </tr>
            </thead>
            <tbody>
              {(selectedClass?.fields || []).map((field, i) => (
                <tr
                  key={i}
                  role="button"
                  tabIndex={0}
                  aria-selected={false}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' || e.key === ' ') {
                      e.preventDefault();
                      if (window.bifrost?.copyWithToast) window.bifrost.copyWithToast(field.name, 'Copied to clipboard');
                    }
                  }}
                >
                  <td className="offset">{fmtOffset(field.offset)}</td>
                  <td>{field.name}</td>
                  <td className="type">{field.type}</td>
                  <td>{field.size ?? '-'}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </>
  );
}
